/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("appAreaObjectPageObjectPage journey");

        opaTest("Navigate to appAreaObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheheaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheheaderListGenerated.onTable().iCheckRows();
            When.onTheheaderListGenerated.onTable().iPressRow(0);

            Then.onTheheaderObjectPageGenerated.iSeeThisPage();
            Then.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iCheckRows();
            When.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iPressRow(0);

            Then.onTheappAreaObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheappAreaObjectPageGenerated.iCheckSection({ section: "AccessAreaInfo" });
            Then.onTheappAreaObjectPageGenerated.onForm({ section: "AccessAreaInfo" }).iCheckField({ property: "AreaCode" });
            Then.onTheappAreaObjectPageGenerated.onForm({ section: "AccessAreaInfo" }).iCheckField({ property: "AreaStatus" });
            Then.onTheappAreaObjectPageGenerated.onForm({ section: "AccessAreaInfo" }).iCheckField({ property: "ApprovedBy" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});