/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("headerListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheheaderListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheheaderListGenerated.onFilterBar().iCheckFilterField("Request Number");
            Then.onTheheaderListGenerated.onFilterBar().iCheckFilterField("Request Type");
            Then.onTheheaderListGenerated.onFilterBar().iCheckFilterField("Payroll Number");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheheaderListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheheaderListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheheaderListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheheaderListGenerated.onTable().iCheckCreate({ visible: true });
            // Then.onTheheaderListGenerated.onTable().iPressCreate();
            // Then.onTheheaderListGenerated.onTable().iPressDelete();
            Then.onTheheaderListGenerated.onTable().iCheckDelete({ visible: true });
            // Then.onTheheaderListGenerated.onTable().iPressAction("Copy Request");
            Then.onTheheaderListGenerated.onTable().iCheckAction("Copy Request", { enabled: false });
            Then.onTheheaderListGenerated.onTable().iCheckColumns(undefined, {"RequestId":{"header":"Request Number"},"ReqType":{"header":"Request Type"},"PayrollNum":{"header":"Payroll Number"},"FullName":{"header":"Full Name"},"BadgeNum":{"header":"Badge Number"},"Status":{"header":"Status"},"Department":{"header":"Department"},"JobTitle":{"header":"Job Title"},"LocationID":{"header":"Location"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheheaderListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheheaderListGenerated.onTable().iCheckRows();

            When.onTheheaderListGenerated.onTable().iPressRow(0);
            Then.onTheheaderObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});