/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("headerObjectPageObjectPage journey");

        opaTest("Navigate to headerObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheheaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheheaderListGenerated.onTable().iCheckRows();
            When.onTheheaderListGenerated.onTable().iPressRow(0);

            Then.onTheheaderObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheheaderObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheheaderObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheheaderObjectPageGenerated.onHeader().iCheckAction("Approve" /* , { enabled: true } */);
            // When.onTheheaderObjectPageGenerated.onHeader().iPressAction("Approve");
            Then.onTheheaderObjectPageGenerated.onHeader().iCheckAction("Reject" /* , { enabled: true } */);
            // When.onTheheaderObjectPageGenerated.onHeader().iPressAction("Reject");
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheheaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "RequestType" });
            Then.onTheheaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Status" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheheaderObjectPageGenerated.iCheckNumberOfSections(5);
            When.onTheheaderObjectPageGenerated.iPressSectionIconTabFilterButton("EmpInfo");
            Then.onTheheaderObjectPageGenerated.iCheckSection({ section: "EmpInfo" });
            When.onTheheaderObjectPageGenerated.iPressSectionIconTabFilterButton("EmpOrg");
            Then.onTheheaderObjectPageGenerated.iCheckSection({ section: "EmpOrg" });
            When.onTheheaderObjectPageGenerated.iPressSectionIconTabFilterButton("ReqDetails");
            Then.onTheheaderObjectPageGenerated.iCheckSection({ section: "ReqDetails" });
            When.onTheheaderObjectPageGenerated.iPressSectionIconTabFilterButton("AreaTab");
            Then.onTheheaderObjectPageGenerated.iCheckSection({ section: "AreaTab" });
            Then.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iCheckAction("Approve Area" /* , { enabled: true } */);
            // When.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iPressAction("Approve Area");
            Then.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iCheckAction("Reject Area" /* , { enabled: true } */);
            // When.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iPressAction("Reject Area");
            Then.onTheheaderObjectPageGenerated.onTable({ property: "_items" }).iCheckColumns(undefined, {"AreaCode":{"header":"Area Code"},"ApprovedBy":{"header":"Approved By"},"AreaStatus":{"header":"Approval Status"}});
            When.onTheheaderObjectPageGenerated.iPressSectionIconTabFilterButton("AppointDetails");
            Then.onTheheaderObjectPageGenerated.iCheckSection({ section: "AppointDetails" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});